///
/// LineString+GeometryTests+XCTest.swift
///
/// Copyright 2016 Tony Stone
///
///  Licensed under the Apache License, Version 2.0 (the "License");
///  you may not use this file except in compliance with the License.
///  You may obtain a copy of the License at
///
///  http://www.apache.org/licenses/LICENSE-2.0
///
///  Unless required by applicable law or agreed to in writing, software
///  distributed under the License is distributed on an "AS IS" BASIS,
///  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
///  See the License for the specific language governing permissions and
///  limitations under the License.
///
///  Created by Tony Stone on 5/4/16.
///
import XCTest

///
/// NOTE: This file was auto generated by file process_test_files.rb.
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension LineString_Geometry_Coordinate2D_FloatingPrecision_Cartesian_Tests {

   static var allTests: [(String, (LineString_Geometry_Coordinate2D_FloatingPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension),
                ("testBoundary_1Element_Invalid", testBoundary_1Element_Invalid),
                ("testBoundary_2Element", testBoundary_2Element),
                ("testBoundary_3Element_Open", testBoundary_3Element_Open),
                ("testBoundary_4Element_Closed", testBoundary_4Element_Closed),
                ("testBoundary_Empty", testBoundary_Empty),
                ("testEqual_True", testEqual_True),
                ("testEqual_False", testEqual_False),
                ("testIsSimple_WithNoPoints", testIsSimple_WithNoPoints),
                ("testIsSimple_WithOnePoint", testIsSimple_WithOnePoint),
                ("testIsSimple_WithTwoPoints", testIsSimple_WithTwoPoints),
                ("testIsSimple_WithThreeIdenticalPoints", testIsSimple_WithThreeIdenticalPoints),
                ("testIsSimple_WithThreePoints_FirstSecondSame", testIsSimple_WithThreePoints_FirstSecondSame),
                ("testIsSimple_WithThreePoints_FirstThirdSame", testIsSimple_WithThreePoints_FirstThirdSame),
                ("testIsSimple_WithThreePoints_SecondThirdSame", testIsSimple_WithThreePoints_SecondThirdSame),
                ("testIsSimple_WithThreePoints_AllDifferent", testIsSimple_WithThreePoints_AllDifferent),
                ("testIsSimple_WithFourPoints_FirstLastSame", testIsSimple_WithFourPoints_FirstLastSame),
                ("testIsSimple_WithFourPoints_LastSegmentTouchesButGoesBeyondFirstPoint", testIsSimple_WithFourPoints_LastSegmentTouchesButGoesBeyondFirstPoint),
                ("testIsSimple_WithFourPoints_LastSegmentCrossedFirstSegment", testIsSimple_WithFourPoints_LastSegmentCrossedFirstSegment),
                ("testIsSimple_WithFivePoints_SecondLastSame", testIsSimple_WithFivePoints_SecondLastSame),
                ("testIsSimple_WithFivePoints_FirstFourthSame", testIsSimple_WithFivePoints_FirstFourthSame),
                ("testIsSimple_WithFivePoints_ThirdSegmentTouchesFirstSegment", testIsSimple_WithFivePoints_ThirdSegmentTouchesFirstSegment),
           ]
   }
}
extension LineString_Geometry_Coordinate2DM_FloatingPrecision_Cartesian_Tests {

   static var allTests: [(String, (LineString_Geometry_Coordinate2DM_FloatingPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension),
           ]
   }
}
extension LineString_Geometry_Coordinate3D_FloatingPrecision_Cartesian_Tests {

   static var allTests: [(String, (LineString_Geometry_Coordinate3D_FloatingPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension),
           ]
   }
}
extension LineString_Geometry_Coordinate3DM_FloatingPrecision_Cartesian_Tests {

   static var allTests: [(String, (LineString_Geometry_Coordinate3DM_FloatingPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension),
           ]
   }
}
extension LineString_Geometry_Coordinate2D_FixedPrecision_Cartesian_Tests {

   static var allTests: [(String, (LineString_Geometry_Coordinate2D_FixedPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension),
                ("testIsSimple_WithNoPoints", testIsSimple_WithNoPoints),
                ("testIsSimple_WithOnePoint", testIsSimple_WithOnePoint),
                ("testIsSimple_WithTwoPoints", testIsSimple_WithTwoPoints),
                ("testIsSimple_WithThreeIdenticalPoints", testIsSimple_WithThreeIdenticalPoints),
                ("testIsSimple_WithThreePoints_FirstSecondSame", testIsSimple_WithThreePoints_FirstSecondSame),
                ("testIsSimple_WithThreePoints_FirstThirdSame", testIsSimple_WithThreePoints_FirstThirdSame),
                ("testIsSimple_WithThreePoints_SecondThirdSame", testIsSimple_WithThreePoints_SecondThirdSame),
                ("testIsSimple_WithThreePoints_AllDifferent", testIsSimple_WithThreePoints_AllDifferent),
                ("testIsSimple_WithFourPoints_FirstLastSame", testIsSimple_WithFourPoints_FirstLastSame),
                ("testIsSimple_WithFourPoints_LastSegmentTouchesButGoesBeyondFirstPoint", testIsSimple_WithFourPoints_LastSegmentTouchesButGoesBeyondFirstPoint),
                ("testIsSimple_WithFourPoints_LastSegmentCrossedFirstSegment", testIsSimple_WithFourPoints_LastSegmentCrossedFirstSegment),
                ("testIsSimple_WithFivePoints_SecondLastSame", testIsSimple_WithFivePoints_SecondLastSame),
                ("testIsSimple_WithFivePoints_FirstFourthSame", testIsSimple_WithFivePoints_FirstFourthSame),
                ("testIsSimple_WithFivePoints_ThirdSegmentTouchesFirstSegment", testIsSimple_WithFivePoints_ThirdSegmentTouchesFirstSegment),
           ]
   }
}
extension LineString_Geometry_Coordinate2DM_FixedPrecision_Cartesian_Tests {

   static var allTests: [(String, (LineString_Geometry_Coordinate2DM_FixedPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension),
           ]
   }
}
extension LineString_Geometry_Coordinate3D_FixedPrecision_Cartesian_Tests {

   static var allTests: [(String, (LineString_Geometry_Coordinate3D_FixedPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension),
           ]
   }
}
extension LineString_Geometry_Coordinate3DM_FixedPrecision_Cartesian_Tests {

   static var allTests: [(String, (LineString_Geometry_Coordinate3DM_FixedPrecision_Cartesian_Tests) -> () throws -> Void)] {
      return [
                ("testDimension", testDimension),
           ]
   }
}
