///
///  MultiPointTests.swift
///
///  Copyright (c) 2016 Tony Stone
///
///  Licensed under the Apache License, Version 2.0 (the "License");
///  you may not use this file except in compliance with the License.
///  You may obtain a copy of the License at
///
///  http://www.apache.org/licenses/LICENSE-2.0
///
///  Unless required by applicable law or agreed to in writing, software
///  distributed under the License is distributed on an "AS IS" BASIS,
///  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
///  See the License for the specific language governing permissions and
///  limitations under the License.
///
///  Created by Tony Stone on 3/6/2016.
///
import XCTest
import GeoFeatures

#if (os(OSX) || os(iOS) || os(tvOS) || os(watchOS)) && SWIFT_PACKAGE
    /// Note: Resolution of GeoFeatures.Polygon is ambiguous when ApplicationsServices is included in the app (ApplicationsServices is used by XCTest), this resolves the ambiguity.
    import struct GeoFeatures.Polygon
#endif

///
/// NOTE: This file was auto generated by gyb from file GeometryCollectionTypesTests.swift.gyb using the following command.
///
/// ../bin/gyb --line-directive '' -DTestInput='MultiPointTestInput' -o MultiPointTests.swift GeometryCollectionTypesTests.swift.gyb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

// MARK: - Coordinate2D, FloatingPrecision, Cartesian -

class MultiPointCoordinate2DFloatingPrecisionCartesianTests: XCTestCase {

    let precision = FloatingPrecision()
    let cs        = Cartesian()

    // MARK: Construction

    func testInitWithNoArg() {
        let input = MultiPoint()

        XCTAssertTrue(input.isEmpty())
    }

    func testInitWithNoArgAndDefaults() {
        let input    = MultiPoint()

        /// FIXME: Currently Precision and CoordinateSystem can not be Equitable and be used for anything other than Generic constraints because it's a protocol, this limits testing of the defaultPrecision and defaultCoordinateSystem
        /// XCTAssertEqual(input.precision as? FloatingPrecision, GeoFeatures.defaultPrecision)
        XCTAssertEqual(input.coordinateSystem as? Cartesian, GeoFeatures.defaultCoordinateSystem)
    }

    func testInitWithPrecisionAndCRS() {
        let input = MultiPoint(precision: precision, coordinateSystem: cs)

        XCTAssertEqual(input.precision as? FloatingPrecision, precision)
        XCTAssertEqual(input.coordinateSystem as? Cartesian, cs)
    }

    func testInitWithPrecision() {
        let input    = MultiPoint(precision: precision)
        let expected = precision

        XCTAssertEqual(input.precision as? FloatingPrecision, expected)
    }

    func testInitWithCRS() {
        let input = MultiPoint(coordinateSystem: cs)
        let expected = cs

        XCTAssertEqual(input.coordinateSystem as? Cartesian, expected)
    }

    // MARK: CustomStringConvertible & CustomDebugStringConvertible

    func testDescription() {

        let input    = MultiPoint(elements: [Point(coordinate: [1.0, 1.0]), Point(coordinate: [2.0, 2.0])], precision: precision, coordinateSystem: cs)
        let expected = "MultiPoint(Point(x: 1.0, y: 1.0), Point(x: 2.0, y: 2.0))"

        XCTAssertEqual(input.description, expected)
    }

    func testDebugDescription() {

        let input    = MultiPoint(elements: [Point(coordinate: [1.0, 1.0]), Point(coordinate: [2.0, 2.0])], precision: precision, coordinateSystem: cs)
        let expected = "MultiPoint(Point(x: 1.0, y: 1.0), Point(x: 2.0, y: 2.0))"

        XCTAssertEqual(input.debugDescription, expected)
    }

    // MARK: Collection conformance
    func testAppend() {

        var input    = MultiPoint(precision: precision, coordinateSystem: cs)
        let expected = [Point(coordinate: [1.0, 1.0])]

        input.append(Point(coordinate: [1.0, 1.0]))

        XCTAssertTrue(input.elementsEqual(expected))
    }

    func testAppendContentsOf() {

        let input1 = MultiPoint(elements: [Point(coordinate: [1.0, 1.0]), Point(coordinate: [2.0, 2.0])], precision: precision, coordinateSystem: cs)
        var input2 = MultiPoint(precision: precision, coordinateSystem: cs)

        input2.append(contentsOf: input1)

        XCTAssertEqual(input1, input2)
    }
    func testInsert2ExistingElements() {

        var input = MultiPoint(elements: [Point(coordinate: [1.0, 1.0]), Point(coordinate: [2.0, 2.0])], precision: precision, coordinateSystem: cs)
        let expected = [Point(coordinate: [2.0, 2.0]), Point(coordinate: [1.0, 1.0]), Point(coordinate: [2.0, 2.0])]

        input.insert(Point(coordinate: [2.0, 2.0]), at: 0)

        XCTAssertTrue(input.elementsEqual(expected))
    }

    func testInsert1ExistingElements() {

        var input = MultiPoint(elements: [Point(coordinate: [1.0, 1.0])], precision: precision, coordinateSystem: cs)
        let expected = [Point(coordinate: [2.0, 2.0]), Point(coordinate: [1.0, 1.0])]

        input.insert(Point(coordinate: [2.0, 2.0]), at: 0)

        XCTAssertTrue(input.elementsEqual(expected))
    }

    // MARK: Swift.Collection Conformance

    func testSubscriptGet() {

        let input    = MultiPoint(elements: [Point(coordinate: [1.0, 1.0]), Point(coordinate: [2.0, 2.0])], precision: precision, coordinateSystem: cs)
        let expected = Point(coordinate: [2.0, 2.0])

        XCTAssertTrue(input[1].equals(expected))
    }

    func testSubscriptSet() {

        var input    = MultiPoint(elements: [Point(coordinate: [1.0, 1.0]), Point(coordinate: [2.0, 2.0])], precision: precision, coordinateSystem: cs)
        let expected = MultiPoint(elements: [Point(coordinate: [1.0, 1.0]), Point(coordinate: [1.0, 1.0])], precision: precision, coordinateSystem: cs)

        input[1] = Point(coordinate: [1.0, 1.0])

        XCTAssertEqual(input, expected)
    }

    func testEquals() {

        let input    = MultiPoint(elements: [Point(coordinate: [1.0, 1.0]), Point(coordinate: [2.0, 2.0])], precision: precision, coordinateSystem: cs)
        let expected = MultiPoint(elements: [Point(coordinate: [1.0, 1.0]), Point(coordinate: [2.0, 2.0])], precision: precision, coordinateSystem: cs)

        XCTAssertEqual(input, expected)
    }

    func testIsEmpty() {

        let input = MultiPoint(precision: precision, coordinateSystem: cs)
        let expected = true

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testIsEmptyFalse() {

        let input    = MultiPoint(elements: [Point(coordinate: [1.0, 1.0]), Point(coordinate: [2.0, 2.0])], precision: precision, coordinateSystem: cs)
        let expected = false

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testCount() {

        let input    = MultiPoint(elements: [Point(coordinate: [1.0, 1.0]), Point(coordinate: [2.0, 2.0])], precision: precision, coordinateSystem: cs)
        let expected = 2

        XCTAssertEqual(input.count, expected)
    }
}

// MARK: - Coordinate2D, FixedPrecision, Cartesian -

class MultiPointCoordinate2DFixedPrecisionCartesianTests: XCTestCase {

    let precision = FixedPrecision(scale: 100)
    let cs        = Cartesian()

    // MARK: Construction

    func testInitWithNoArg() {
        let input = MultiPoint()

        XCTAssertTrue(input.isEmpty())
    }

    func testInitWithNoArgAndDefaults() {
        let input    = MultiPoint()

        /// FIXME: Currently Precision and CoordinateSystem can not be Equitable and be used for anything other than Generic constraints because it's a protocol, this limits testing of the defaultPrecision and defaultCoordinateSystem
        /// XCTAssertEqual(input.precision as? FixedPrecision, GeoFeatures.defaultPrecision)
        XCTAssertEqual(input.coordinateSystem as? Cartesian, GeoFeatures.defaultCoordinateSystem)
    }

    func testInitWithPrecisionAndCRS() {
        let input = MultiPoint(precision: precision, coordinateSystem: cs)

        XCTAssertEqual(input.precision as? FixedPrecision, precision)
        XCTAssertEqual(input.coordinateSystem as? Cartesian, cs)
    }

    func testInitWithPrecision() {
        let input    = MultiPoint(precision: precision)
        let expected = precision

        XCTAssertEqual(input.precision as? FixedPrecision, expected)
    }

    func testInitWithCRS() {
        let input = MultiPoint(coordinateSystem: cs)
        let expected = cs

        XCTAssertEqual(input.coordinateSystem as? Cartesian, expected)
    }

    // MARK: CustomStringConvertible & CustomDebugStringConvertible

    func testDescription() {

        let input    = MultiPoint(elements: [Point(coordinate: [1.001, 1.001]), Point(coordinate: [2.002, 2.002])], precision: precision, coordinateSystem: cs)
        let expected = "MultiPoint(Point(x: 1.0, y: 1.0), Point(x: 2.0, y: 2.0))"

        XCTAssertEqual(input.description, expected)
    }

    func testDebugDescription() {

        let input    = MultiPoint(elements: [Point(coordinate: [1.001, 1.001]), Point(coordinate: [2.002, 2.002])], precision: precision, coordinateSystem: cs)
        let expected = "MultiPoint(Point(x: 1.0, y: 1.0), Point(x: 2.0, y: 2.0))"

        XCTAssertEqual(input.debugDescription, expected)
    }

    // MARK: Collection conformance
    func testAppend() {

        var input    = MultiPoint(precision: precision, coordinateSystem: cs)
        let expected = [Point(coordinate: [1.0, 1.0])]

        input.append(Point(coordinate: [1.001, 1.001]))

        XCTAssertTrue(input.elementsEqual(expected))
    }

    func testAppendContentsOf() {

        let input1 = MultiPoint(elements: [Point(coordinate: [1.001, 1.001]), Point(coordinate: [2.002, 2.002])], precision: precision, coordinateSystem: cs)
        var input2 = MultiPoint(precision: precision, coordinateSystem: cs)

        input2.append(contentsOf: input1)

        XCTAssertEqual(input1, input2)
    }
    func testInsert2ExistingElements() {

        var input = MultiPoint(elements: [Point(coordinate: [1.001, 1.001]), Point(coordinate: [2.002, 2.002])], precision: precision, coordinateSystem: cs)
        let expected = [Point(coordinate: [2.0, 2.0]), Point(coordinate: [1.0, 1.0]), Point(coordinate: [2.0, 2.0])]

        input.insert(Point(coordinate: [2.002, 2.002]), at: 0)

        XCTAssertTrue(input.elementsEqual(expected))
    }

    func testInsert1ExistingElements() {

        var input = MultiPoint(elements: [Point(coordinate: [1.001, 1.001])], precision: precision, coordinateSystem: cs)
        let expected = [Point(coordinate: [2.0, 2.0]), Point(coordinate: [1.0, 1.0])]

        input.insert(Point(coordinate: [2.002, 2.002]), at: 0)

        XCTAssertTrue(input.elementsEqual(expected))
    }

    // MARK: Swift.Collection Conformance

    func testSubscriptGet() {

        let input    = MultiPoint(elements: [Point(coordinate: [1.001, 1.001]), Point(coordinate: [2.002, 2.002])], precision: precision, coordinateSystem: cs)
        let expected = Point(coordinate: [2.0, 2.0])

        XCTAssertTrue(input[1].equals(expected))
    }

    func testSubscriptSet() {

        var input    = MultiPoint(elements: [Point(coordinate: [1.001, 1.001]), Point(coordinate: [2.002, 2.002])], precision: precision, coordinateSystem: cs)
        let expected = MultiPoint(elements: [Point(coordinate: [1.0, 1.0]), Point(coordinate: [1.0, 1.0])], precision: precision, coordinateSystem: cs)

        input[1] = Point(coordinate: [1.001, 1.001])

        XCTAssertEqual(input, expected)
    }

    func testEquals() {

        let input    = MultiPoint(elements: [Point(coordinate: [1.001, 1.001]), Point(coordinate: [2.002, 2.002])], precision: precision, coordinateSystem: cs)
        let expected = MultiPoint(elements: [Point(coordinate: [1.0, 1.0]), Point(coordinate: [2.0, 2.0])], precision: precision, coordinateSystem: cs)

        XCTAssertEqual(input, expected)
    }

    func testIsEmpty() {

        let input = MultiPoint(precision: precision, coordinateSystem: cs)
        let expected = true

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testIsEmptyFalse() {

        let input    = MultiPoint(elements: [Point(coordinate: [1.001, 1.001]), Point(coordinate: [2.002, 2.002])], precision: precision, coordinateSystem: cs)
        let expected = false

        XCTAssertEqual(input.isEmpty(), expected)
    }

    func testCount() {

        let input    = MultiPoint(elements: [Point(coordinate: [1.001, 1.001]), Point(coordinate: [2.002, 2.002])], precision: precision, coordinateSystem: cs)
        let expected = 2

        XCTAssertEqual(input.count, expected)
    }
}
