///
///  GeometryCollection.swift
///
///  Copyright (c) 2016 Tony Stone
///
///  Licensed under the Apache License, Version 2.0 (the "License");
///  you may not use this file except in compliance with the License.
///  You may obtain a copy of the License at
///
///  http://www.apache.org/licenses/LICENSE-2.0
///
///  Unless required by applicable law or agreed to in writing, software
///  distributed under the License is distributed on an "AS IS" BASIS,
///  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
///  See the License for the specific language governing permissions and
///  limitations under the License.
///
///  Created by Tony Stone on 2/14/2016.
///
import Swift

///
/// NOTE: This file was auto generated by gyb from file GeometryCollection.swift.gyb using the following command.
///
///     ~/gyb --line-directive '' -DSelf=GeometryCollection -DElement=Geometry -o GeometryCollection.swift GeometryCollection.swift.gyb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

///
/// GeometryCollection
///
/// A GeometryCollection is a collection of some number of Geometry objects.
///
/// All the elements in a GeometryCollection shall be in the same Spatial Reference System. This is also the Spatial Reference System for the GeometryCollection.
///
public struct GeometryCollection {

    public let precision: Precision
    public let coordinateSystem: CoordinateSystem

    ///
    /// Construct an empty `GeometryCollection`.
    ///
    /// - parameters:
    ///     - precision: The `Precision` model this `GeometryCollection` should use in calculations on it's coordinates.
    ///     - coordinateSystem: The 'CoordinateSystem` this `GeometryCollection` should use in calculations on it's coordinates.
    ///
    /// - seealso: `CoordinateSystem`
    /// - seealso: `Precision`
    ///
    public init(precision: Precision = defaultPrecision, coordinateSystem: CoordinateSystem = defaultCoordinateSystem) {
        self.init(elements: [] as [Geometry], precision: precision, coordinateSystem: coordinateSystem)
    }

    ///
    /// Construct a `GeometryCollection` from a any `Collection` type which holds `Element` objects.
    ///
    /// GeometryCollection can be constructed from any Swift.Collection type as
    /// long as it has an Element type equal the Geometry type specified in Element.
    ///
    /// - parameters:
    ///     - elements: A `Collection` of `Element`s.
    ///     - precision: The `Precision` model this `GeometryCollection` should use in calculations on it's coordinates.
    ///     - coordinateSystem: The 'CoordinateSystem` this `GeometryCollection` should use in calculations on it's coordinates.
    ///
    /// - seealso: `CoordinateSystem`
    /// - seealso: `Precision`
    ///
    public init<C: Swift.Collection>(elements: C, precision: Precision = defaultPrecision, coordinateSystem: CoordinateSystem = defaultCoordinateSystem)
            where C.Element == Geometry {

        self.precision = precision
        self.coordinateSystem = coordinateSystem

        self.elements = []

        var Iterator = elements.makeIterator()

        while let element = Iterator.next() {
            /// TODO: Create a new instance to adjust the precision of the new geometry to `GeometryCollection`s precision.
            self.elements.append(element)
        }
    }

    internal private(set) var elements: [Geometry]
}

// MARK: - Copy Construction

internal extension GeometryCollection {

    ///
    /// Construct a GeometryCollection from another GeometryCollection (copy constructor) changing the precision and coordinateSystem.
    ///
    /// - parameters:
    ///     - other: The GeometryCollection of the same type that you want to construct a new GeometryCollection from.
    ///     - precision: Optionally change the `Precision` model this `GeometryCollection` should use in calculations on it's coordinates.
    ///     - coordinateSystem: Optionally change the 'CoordinateSystem` this `GeometryCollection` should use in calculations on it's coordinates.
    ///
    /// - seealso: `CoordinateSystem`
    /// - seealso: `Precision`
    ///
    internal init(other: GeometryCollection, precision: Precision, coordinateSystem: CoordinateSystem) {
        self.init(elements: other.elements, precision: precision, coordinateSystem: coordinateSystem)
    }
}

// MARK: - Collection conformance

extension GeometryCollection: Collection, MutableCollection {

    ///
    /// Returns the position immediately after `i`.
    ///
    /// - Precondition: `(startIndex..<endIndex).contains(i)`
    ///
    public func index(after i: Int) -> Int {
        return i+1
    }

    ///
    /// Always zero, which is the index of the first element when non-empty.
    ///
    public var startIndex: Int {
       return 0
    }

    ///
    /// A "past-the-end" element index; the successor of the last valid subscript argument.
    ///
    public var endIndex: Int {
        return elements.count
    }

    public subscript(index: Int) -> Geometry {
        get {
            /// Note: we rely on the array to return an error for any index out of range.
            return elements[index]
        }
        set (newElement) {
            /// Note: we rely on the array to return an error for any index out of range.
            /// TODO: Create a new instance to adjust the precision of the new geometry to `GeometryCollection`s precision.
            self.elements[index] = newElement
        }
    }

    ///
    /// Append `newElement` to GeometryCollection.
    ///
    public mutating func append(_ newElement: Geometry) {

        /// TODO: Create a new instance to adjust the precision of the new geometry to `GeometryCollection`s precision.
        self.elements.append(newElement)
    }

    ///
    /// Append the elements of `newElements` to this GeometryCollection.
    ///
    public mutating func append<C: Swift.Collection>(contentsOf newElements: C)
            where C.Element == Geometry {

        var Iterator = newElements.makeIterator()

        while let element = Iterator.next() {
            self.append(element)
        }
    }

    ///
    /// Insert `newElement` at index `i` of this GeometryCollection.
    ///
    /// - Requires: `i <= count`.
    ///
    public mutating func insert(_ newElement: Geometry, at index: Int) {

        /// TODO: Create a new instance to adjust the precision of the new geometry to `GeometryCollection`s precision.
        self.elements.insert(newElement, at: index)
    }
}

// MARK: CustomStringConvertible & CustomDebugStringConvertible protocol conformance

extension GeometryCollection: CustomStringConvertible, CustomDebugStringConvertible {

    public var description: String {
        return "\(type(of: self))(\(self.map { String(describing: $0) }.joined(separator: ", ")))"
    }

    public var debugDescription: String {
        return self.description
    }
}

// MARK: - Equatable Conformance

extension GeometryCollection: Equatable {
    static public func == (lhs: GeometryCollection, rhs: GeometryCollection) -> Bool {
        return lhs.equals(rhs)
    }
}


