///
///  MultiLineString.swift
///
///  Copyright (c) 2016 Tony Stone
///
///  Licensed under the Apache License, Version 2.0 (the "License");
///  you may not use this file except in compliance with the License.
///  You may obtain a copy of the License at
///
///  http://www.apache.org/licenses/LICENSE-2.0
///
///  Unless required by applicable law or agreed to in writing, software
///  distributed under the License is distributed on an "AS IS" BASIS,
///  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
///  See the License for the specific language governing permissions and
///  limitations under the License.
///
///  Created by Tony Stone on 2/14/2016.
///

///
/// NOTE: This file was auto generated by gyb from file GeometryCollectionTypes.swift.gyb using the following command.
///
///     ~/gyb --line-directive '' -DSelf=MultiLineString -DElement=LineString -o MultiLineString.swift GeometryCollectionTypes.swift.gyb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///
import Swift

///
/// A MultiLineString is a collection of some number of LineString objects.
///
/// All the elements in a MultiLineString will be converted to the same Spatial Reference System as `self`.
///
public struct MultiLineString: Geometry {

    ///
    /// The `Precision` of this MultiLineString
	///
    public let precision: Precision

    ///
    /// The `CoordinateSystem` of this MultiLineString
	///
    public let coordinateSystem: CoordinateSystem

    ///
    /// Construct an empty `MultiLineString`.
    ///
    public init() {
        self.init([], precision: defaultPrecision, coordinateSystem: defaultCoordinateSystem)
    }

    ///
    /// Construct an empty `MultiLineString`.
    ///
    /// - Parameters:
    ///     - precision: The `Precision` model this `MultiLineString` should use in calculations on it's coordinates.
    ///     - coordinateSystem: The 'CoordinateSystem` this `MultiLineString` should use in calculations on it's coordinates.
	///
    public init(precision: Precision = defaultPrecision, coordinateSystem: CoordinateSystem = defaultCoordinateSystem) {
        self.init([] as [LineString], precision: precision, coordinateSystem: coordinateSystem)
    }

    ///
    /// Construct a MultiLineString from another MultiLineString (copy constructor) changing the precision and coordinateSystem.
    ///
    /// - Parameters:
    ///     - other: The MultiLineString of the same type that you want to construct a new MultiLineString from.
    ///     - precision: Optionally change the `Precision` model this `MultiLineString` should use in calculations on it's coordinates.
    ///     - coordinateSystem: Optionally change the 'CoordinateSystem` this `MultiLineString` should use in calculations on it's coordinates.
	///
    public init(other: MultiLineString, precision: Precision = defaultPrecision, coordinateSystem: CoordinateSystem = defaultCoordinateSystem) {
        self.init(other.elements, precision: precision, coordinateSystem: coordinateSystem)
    }

    ///
    /// Construct a `MultiLineString` from an `Array` which holds `LineString` objects.
    ///
    /// MultiLineString can be constructed from any Swift.Collection type as
    /// long as it has an Element type equal the Geometry type specified in Element.
    ///
    /// - Parameters:
    ///     - elements: An `Array` of `LineString`s.
    ///     - precision: The `Precision` model this `MultiLineString` should use in calculations on it's coordinates.
    ///     - coordinateSystem: The 'CoordinateSystem` this `MultiLineString` should use in calculations on it's coordinates.
	///
    public init(_ elements: [LineString], precision: Precision = defaultPrecision, coordinateSystem: CoordinateSystem = defaultCoordinateSystem) {

        self.precision        = precision
        self.coordinateSystem = coordinateSystem

        /// Add the elements to our backing storage
        self.replaceSubrange(0..<0, with: elements)
    }

    private var elements: [LineString] = []
}

// MARK: - ExpressibleByArrayLiteral conformance

extension MultiLineString: ExpressibleByArrayLiteral {

    /// Creates an instance initialized with the given elements.
    public init(arrayLiteral elements: LineString...) {
        self.init(elements)
    }
}

// MARK: - `GeometryCollectionType` and `RangeReplaceableCollection` conformance.

extension MultiLineString: GeometryCollectionType, RangeReplaceableCollection {

    ///
    /// Returns the position immediately after `i`.
    ///
    /// - Precondition: `(startIndex..<endIndex).contains(i)`
    ///
    public func index(after i: Int) -> Int {
        return i+1
    }

    ///
    /// Always zero, which is the index of the first element when non-empty.
    ///
    public var startIndex: Int {
       return 0
    }

    ///
    /// A "past-the-end" element index; the successor of the last valid subscript argument.
    ///
    public var endIndex: Int {
        return elements.count
    }

    ///
    /// Accesses the element at the specified position.
    ///
    public subscript(index: Int) -> LineString {
        get {
            /// Note: we rely on the array to return an error for any index out of range.
            return elements[index]
        }
        set (newElement) {
            self.replaceSubrange(index..<(index + 1), with: [newElement])
        }
    }

    ///
    /// Replaces the specified subrange of elements with the given collection.
    ///
    /// This method has the effect of removing the specified range of elements
    /// from the collection and inserting the new elements at the same location.
    /// The number of new elements need not match the number of elements being
    /// removed.
    ///
    public mutating func replaceSubrange<C, R>(_ subrange: R, with newElements: C) where C : Collection, R : RangeExpression, LineString == C.Element, Int == R.Bound {
        let preciseElements = newElements.map({ LineString(other: $0, precision: self.precision, coordinateSystem: self.coordinateSystem) })

        self.elements.replaceSubrange(subrange, with: preciseElements)
    }
}

// MARK: CustomStringConvertible & CustomDebugStringConvertible protocol conformance

extension MultiLineString: CustomStringConvertible, CustomDebugStringConvertible {

    public var description: String {
        return "\(type(of: self))([\(self.map { String(describing: $0) }.joined(separator: ", "))])"
    }

    public var debugDescription: String {
        return self.description
    }
}

// MARK: - Equatable Conformance

extension MultiLineString: Equatable {
    static public func == (lhs: MultiLineString, rhs: MultiLineString) -> Bool {
        return lhs.elementsEqual(rhs)
    }
}
