///
///  MultiPoint.swift
///
///  Copyright (c) 2016 Tony Stone
///
///  Licensed under the Apache License, Version 2.0 (the "License");
///  you may not use this file except in compliance with the License.
///  You may obtain a copy of the License at
///
///  http://www.apache.org/licenses/LICENSE-2.0
///
///  Unless required by applicable law or agreed to in writing, software
///  distributed under the License is distributed on an "AS IS" BASIS,
///  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
///  See the License for the specific language governing permissions and
///  limitations under the License.
///
///  Created by Tony Stone on 2/14/2016.
///
import Swift

///
/// NOTE: This file was auto generated by gyb from file GeometryCollection.swift.gyb using the following command.
///
///     ~/gyb --line-directive '' -DSelf=MultiPoint -DElement=Point<CoordinateType> -DCoordinateSpecialized=true -o MultiPoint.swift GeometryCollection.swift.gyb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

///
/// MultiPoint
///
/// A MultiPoint is a collection of some number of Point<CoordinateType> objects.
///
/// All the elements in a MultiPoint shall be in the same Spatial Reference System. This is also the Spatial Reference System for the MultiPoint.
///
public struct MultiPoint<CoordinateType: Coordinate & CopyConstructable> {

    public let precision: Precision
    public let coordinateSystem: CoordinateSystem

    ///
    /// Construct an empty `MultiPoint`.
    ///
    /// - parameters:
    ///     - precision: The `Precision` model this `MultiPoint` should use in calculations on it's coordinates.
    ///     - coordinateSystem: The 'CoordinateSystem` this `MultiPoint` should use in calculations on it's coordinates.
    ///
    /// - seealso: `CoordinateSystem`
    /// - seealso: `Precision`
    ///
    public init(precision: Precision = defaultPrecision, coordinateSystem: CoordinateSystem = defaultCoordinateSystem) {
        self.precision        = precision
        self.coordinateSystem = coordinateSystem
        self.elements         = []
    }

    ///
    /// Construct a MultiPoint from another MultiPoint (copy constructor).
    ///
    /// - parameters:
    ///     - other: The MultiPoint of the same type that you want to construct a new MultiPoint from.
    ///
    public init(other: MultiPoint<CoordinateType>) {

        self.precision        = other.precision
        self.coordinateSystem = other.coordinateSystem
        self.elements         = other.elements
    }

    ///
    /// Construct a MultiPoint from another MultiPoint (copy constructor) changing the precision and coordinateSystem.
    ///
    /// - parameters:
    ///     - other: The MultiPoint of the same type that you want to construct a new MultiPoint from.
    ///     - precision: Optionally change the `Precision` model this `MultiPoint` should use in calculations on it's coordinates.
    ///     - coordinateSystem: Optionally change the 'CoordinateSystem` this `MultiPoint` should use in calculations on it's coordinates.
    ///
    /// - seealso: `CoordinateSystem`
    /// - seealso: `Precision`
    ///
    internal init(other: MultiPoint<CoordinateType>, precision: Precision, coordinateSystem: CoordinateSystem) {

        self.precision        = precision
        self.coordinateSystem = coordinateSystem

        /// We create a new instance of the Point<CoordinateType> so we can adjust the precision and Coordinate reference system of the Point<CoordinateType> before adding.
        self.elements         = other.elements.map({ Point<CoordinateType>(other: $0, precision: precision, coordinateSystem: coordinateSystem) })
    }

    ///
    /// Construct a `MultiPoint` from a an `Array` of `Point<CoordinateType>`.
    ///
    /// - parameters:
    ///     - elements: An `Array` of `Point<CoordinateType>` coordinates.
    ///     - precision: The `Precision` model this `MultiPoint` should use in calculations on it's coordinates.
    ///     - coordinateSystem: The 'CoordinateSystem` this `MultiPoint` should use in calculations on it's coordinates.
    ///
    /// - seealso: `CoordinateSystem`
    /// - seealso: `Precision`
    ///
    public init(elements: [Point<CoordinateType>], precision: Precision = defaultPrecision, coordinateSystem: CoordinateSystem = defaultCoordinateSystem) {

        self.precision        = precision
        self.coordinateSystem = coordinateSystem

        /// We create a new instance of the Point<CoordinateType> so we can adjust the precision and Coordinate reference system of the Point<CoordinateType> before adding.
        self.elements         = elements.map({ Point<CoordinateType>(other: $0, precision: precision, coordinateSystem: coordinateSystem) })
    }

    ///
    /// Construct a `MultiPoint` from a any `Collection` type which holds `Element` objects.
    ///
    /// MultiPoint can be constructed from any Swift.Collection type as
    /// long as it has an Element type equal the Geometry type specified in Element.
    ///
    /// - parameters:
    ///     - elements: A `Collection` of `Element`s.
    ///     - precision: The `Precision` model this `MultiPoint` should use in calculations on it's coordinates.
    ///     - coordinateSystem: The 'CoordinateSystem` this `MultiPoint` should use in calculations on it's coordinates.
    ///
    /// - seealso: `CoordinateSystem`
    /// - seealso: `Precision`
    ///
    public init<C: Swift.Collection>(elements: C, precision: Precision = defaultPrecision, coordinateSystem: CoordinateSystem = defaultCoordinateSystem)
            where C.Iterator.Element == Point<CoordinateType> {

        self.precision = precision
        self.coordinateSystem = coordinateSystem

        /// We create a new instance of the Point<CoordinateType> so we can adjust the precision and Coordinate reference system of the Point<CoordinateType> before adding.
        self.elements = elements.map({ Point<CoordinateType>(other: $0, precision: precision, coordinateSystem: coordinateSystem) })
    }

    internal private(set) var elements: [Point<CoordinateType>]
}

// MARK: - Collection conformance

extension MultiPoint: Collection, MutableCollection {

    ///
    /// Returns the position immediately after `i`.
    ///
    /// - Precondition: `(startIndex..<endIndex).contains(i)`
    ///
    public func index(after i: Int) -> Int {
        return i+1
    }

    ///
    /// Always zero, which is the index of the first element when non-empty.
    ///
    public var startIndex: Int {
       return 0
    }

    ///
    /// A "past-the-end" element index; the successor of the last valid subscript argument.
    ///
    public var endIndex: Int {
        return elements.count
    }

    public subscript(index: Int) -> Point<CoordinateType> {
        get {
            /// Note: we rely on the array to return an error for any index out of range.
            return elements[index]
        }
        set (newElement) {
            /// Note: we rely on the array to return an error for any index out of range.
            /// We create a new instance of the Point<CoordinateType> so we can adjust the precision and Coordinate reference system of the Point<CoordinateType> before adding.
            self.elements[index] = Point<CoordinateType>(other: newElement, precision: self.precision, coordinateSystem: self.coordinateSystem)
        }
    }

    ///
    /// Append `newElement` to MultiPoint.
    ///
    public mutating func append(_ newElement: Point<CoordinateType>) {

        /// We create a new instance of the Point<CoordinateType> so we can adjust the precision and Coordinate reference system of the Point<CoordinateType> before adding.
        self.elements.append(Point<CoordinateType>(other: newElement, precision: self.precision, coordinateSystem: self.coordinateSystem))
    }

    ///
    /// Append the elements of `newElements` to this MultiPoint.
    ///
    public mutating func append<C: Swift.Collection>(contentsOf newElements: C)
            where C.Iterator.Element == Point<CoordinateType> {

        var Iterator = newElements.makeIterator()

        while let element = Iterator.next() {
            self.append(element)
        }
    }

    ///
    /// Insert `newElement` at index `i` of this MultiPoint.
    ///
    /// - Requires: `i <= count`.
    ///
    public mutating func insert(_ newElement: Point<CoordinateType>, at index: Int) {

        /// We create a new instance of the Point<CoordinateType> so we can adjust the precision and Coordinate reference system of the Point<CoordinateType> before adding.
        self.elements.insert(Point<CoordinateType>(other: newElement, precision: self.precision, coordinateSystem: self.coordinateSystem), at: index)
    }
}

// MARK: CustomStringConvertible & CustomDebugStringConvertible protocol conformance

extension MultiPoint: CustomStringConvertible, CustomDebugStringConvertible {

    public var description: String {
        return "\(type(of: self))(\(self.map { String(describing: $0) }.joined(separator: ", ")))"
    }

    public var debugDescription: String {
        return self.description
    }
}

// MARK: - Equatable Conformance

extension MultiPoint: Equatable {}

public func == <CoordinateType>(lhs: MultiPoint<CoordinateType>, rhs: MultiPoint<CoordinateType>) -> Bool {
    return lhs.equals(rhs)
}
