///
///  MultiPoint.swift
///
///  Copyright (c) 2016 Tony Stone
///
///  Licensed under the Apache License, Version 2.0 (the "License");
///  you may not use this file except in compliance with the License.
///  You may obtain a copy of the License at
///
///  http://www.apache.org/licenses/LICENSE-2.0
///
///  Unless required by applicable law or agreed to in writing, software
///  distributed under the License is distributed on an "AS IS" BASIS,
///  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
///  See the License for the specific language governing permissions and
///  limitations under the License.
///
///  Created by Tony Stone on 2/14/2016.
///
import Swift

///
/// NOTE: This file was auto generated by gyb from file GeometryCollectionTypes.swift.gyb using the following command.
///
///     ~/gyb --line-directive '' -DSelf=MultiPoint -DElement=Point -o MultiPoint.swift GeometryCollectionTypes.swift.gyb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

///
/// MultiPoint
///
/// A MultiPoint is a collection of some number of Point objects.
///
/// All the elements in a MultiPoint shall be in the same Spatial Reference System. This is also the Spatial Reference System for the MultiPoint.
///
public struct MultiPoint {

    ///
    /// - returns: The `Precision` of this MultiPoint
    ///
    /// - SeeAlso: `Precision`
    ///
    public let precision: Precision

    ///
    /// - returns: The `CoordinateSystem` of this MultiPoint
    ///
    /// - SeeAlso: `CoordinateSystem`
    ///
    public let coordinateSystem: CoordinateSystem

    ///
    /// Construct an empty `MultiPoint`.
    ///
    public init() {
        self.init([], precision: defaultPrecision, coordinateSystem: defaultCoordinateSystem)
    }

    ///
    /// Construct an empty `MultiPoint`.
    ///
    /// - Parameters:
    ///     - precision: The `Precision` model this `MultiPoint` should use in calculations on it's coordinates.
    ///     - coordinateSystem: The 'CoordinateSystem` this `MultiPoint` should use in calculations on it's coordinates.
    ///
    /// - SeeAlso: `CoordinateSystem`
    /// - SeeAlso: `Precision`
    ///
    public init(precision: Precision = defaultPrecision, coordinateSystem: CoordinateSystem = defaultCoordinateSystem) {
        self.init([] as [Point], precision: precision, coordinateSystem: coordinateSystem)
    }

    ///
    /// Construct a MultiPoint from another MultiPoint (copy constructor) changing the precision and coordinateSystem.
    ///
    /// - Parameters:
    ///     - other: The MultiPoint of the same type that you want to construct a new MultiPoint from.
    ///     - precision: Optionally change the `Precision` model this `MultiPoint` should use in calculations on it's coordinates.
    ///     - coordinateSystem: Optionally change the 'CoordinateSystem` this `MultiPoint` should use in calculations on it's coordinates.
    ///
    /// - SeeAlso: `CoordinateSystem`
    /// - SeeAlso: `Precision`
    ///
    public init(other: MultiPoint, precision: Precision = defaultPrecision, coordinateSystem: CoordinateSystem = defaultCoordinateSystem) {
        self.init(other.elements, precision: precision, coordinateSystem: coordinateSystem)
    }

    ///
    /// Construct a `MultiPoint` from an `Array` which holds `Point` objects.
    ///
    /// MultiPoint can be constructed from any Swift.Collection type as
    /// long as it has an Element type equal the Geometry type specified in Element.
    ///
    /// - Parameters:
    ///     - elements: An `Array` of `Point`s.
    ///     - precision: The `Precision` model this `MultiPoint` should use in calculations on it's coordinates.
    ///     - coordinateSystem: The 'CoordinateSystem` this `MultiPoint` should use in calculations on it's coordinates.
    ///
    /// - SeeAlso: `CoordinateSystem`
    /// - SeeAlso: `Precision`
    ///
    public init(_ elements: [Point], precision: Precision = defaultPrecision, coordinateSystem: CoordinateSystem = defaultCoordinateSystem) {

        self.precision        = precision
        self.coordinateSystem = coordinateSystem

        /// Add the elements to our backing storage
        self.replaceSubrange(0..<0, with: elements)
    }

    private var elements: [Point] = []
}

// MARK: - ExpressibleByArrayLiteral conformance

extension MultiPoint: ExpressibleByArrayLiteral {

    /// Creates an instance initialized with the given elements.
    public init(arrayLiteral elements: Point...) {
        self.init(elements)
    }
}

// MARK: - `GeometryCollectionType` and `RangeReplaceableCollection` conformance.

extension MultiPoint: GeometryCollectionType, RangeReplaceableCollection {

    ///
    /// Returns the position immediately after `i`.
    ///
    /// - Precondition: `(startIndex..<endIndex).contains(i)`
    ///
    public func index(after i: Int) -> Int {
        return i+1
    }

    ///
    /// Always zero, which is the index of the first element when non-empty.
    ///
    public var startIndex: Int {
       return 0
    }

    ///
    /// A "past-the-end" element index; the successor of the last valid subscript argument.
    ///
    public var endIndex: Int {
        return elements.count
    }

    ///
    /// Accesses the element at the specified position.
    ///
    public subscript(index: Int) -> Point {
        get {
            /// Note: we rely on the array to return an error for any index out of range.
            return elements[index]
        }
        set (newElement) {
            self.replaceSubrange(index..<(index + 1), with: [newElement])
        }
    }

    ///
    /// Replaces the specified subrange of elements with the given collection.
    ///
    /// This method has the effect of removing the specified range of elements
    /// from the collection and inserting the new elements at the same location.
    /// The number of new elements need not match the number of elements being
    /// removed.
    ///
    public mutating func replaceSubrange<C, R>(_ subrange: R, with newElements: C) where C : Collection, R : RangeExpression, Point == C.Element, Int == R.Bound {
        let preciseElements = newElements.map({ Point(other: $0, precision: self.precision, coordinateSystem: self.coordinateSystem) })

        self.elements.replaceSubrange(subrange, with: preciseElements)
    }
}

// MARK: CustomStringConvertible & CustomDebugStringConvertible protocol conformance

extension MultiPoint: CustomStringConvertible, CustomDebugStringConvertible {

    public var description: String {
        return "\(type(of: self))([\(self.map { String(describing: $0) }.joined(separator: ", "))])"
    }

    public var debugDescription: String {
        return self.description
    }
}

// MARK: - Equatable Conformance

extension MultiPoint: Equatable {
    static public func == (lhs: MultiPoint, rhs: MultiPoint) -> Bool {
        return lhs.equals(rhs)
    }
}
